---
abstract: 'manage a bitcoin instance'
author:
  - 'Toby Inkster <tobyink@cpan.org>'
build_requires:
  ExtUtils::MakeMaker: 6.59
configure_requires:
  ExtUtils::MakeMaker: 6.59
distribution_type: module
dynamic_config: 0
generated_by: 'Module::Install version 1.06'
keywords:
  - Bitcoin
  - Commerce
  - Currancy
  - Currency
  - Finance
  - JSON-RPC
  - JSONRPC
  - Micropayment
  - Micropayments
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
module_name: Finance::Bitcoin
name: Finance-Bitcoin
no_index:
  directory:
    - examples
    - inc
    - t
    - xt
requires:
  JSON::RPC::Client: 0.93
  Moo: 0
  Object::AUTHORITY: 0
  perl: 5.10.0
resources:
  bugtracker: http://rt.cpan.org/Dist/Display.html?Queue=Finance-Bitcoin
  homepage: https://metacpan.org/release/Finance-Bitcoin
  license: http://dev.perl.org/licenses/
  repository: http://goddamn.co.uk/svn-web/perlmods/browse/Finance-Bitcoin/
version: 0.900
